### ISSUE TITLE
2.C Refactor Chirp.CLI's Program.cs so that all User Interface code resides in a separate class

### ISSUE THREAD

**Issue by BastianGram** [ITU-BDSA2024-GROUP11/Chirp#1]
In ordrer to make the codebase more readable as a coder, I can refactor all code that is concerned with printing cheeps to the terminal into a separate class called UserInterface.

Likely, it is a good design to make the UserInterface and the contained methods [static](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/static-classes-and-static-class-members) 💯

**Comment by NewNorthStar** [comment]
Remember to designate Acceptance criteria, and add a label on the right to indicate which type of issue it is.

**Comment by AndrxB** [comment]
o7

**Comment by BastianGram** [comment]
> Remember to designate Acceptance criteria, and add a label on the right to indicate which type of issue it is.

Du lukker bare bøtten
